openapi: 3.0.3
info:
    title: Laravel
    description: ''
    version: 1.0.0
servers:
    -
        url: 'http://localhost'
paths:
    /admin/medicines:
        get:
            summary: 'Medicine View'
            description: 'This returns the view of medicine'
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                302:
                    description: ''
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: "<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"0;url='http://localhost/admin/login'\" />\n\n        <title>Redirecting to http://localhost/admin/login</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"http://localhost/admin/login\">http://localhost/admin/login</a>.\n    </body>\n</html>"
            tags:
                - 'Admin Controller'
    '/admin/add-edit-medicine/{id}':
        get:
            summary: 'Add or Edit Medicine'
            description: 'Can add or edit or delete medicine'
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                302:
                    description: ''
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: "<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"0;url='http://localhost/admin/login'\" />\n\n        <title>Redirecting to http://localhost/admin/login</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"http://localhost/admin/login\">http://localhost/admin/login</a>.\n    </body>\n</html>"
            tags:
                - 'Admin Controller'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                manufacturerId:
                                    type: number
                                    description: 'Id of the manufacturer.'
                                    example: !!float 1
                                medicineName:
                                    type: string
                                    description: 'Name of the medicine.'
                                    example: Alatrol
                                generic:
                                    type: string
                                    description: 'Generic of the Medicine.'
                                    example: 'Cetirizine Hydrochloride'
                                type:
                                    type: string
                                    description: 'Type of the Medicine.'
                                    example: Tablet
                                quantity:
                                    type: number
                                    description: 'Units per Pata.'
                                    example: !!float 10
                                dose:
                                    type: string
                                    description: 'Dosage of the Medicine per unit.'
                                    example: '2.5 mg'
                                medicinePrice:
                                    type: number
                                    description: 'Price of the Medicine.'
                                    example: !!float 35
                                stock:
                                    type: number
                                    description: 'Stock of the Medicine.'
                                    example: !!float 100
                            required:
                                - medicineName
                                - generic
                                - type
                                - quantity
                                - dose
                                - medicinePrice
                                - stock
        parameters:
            -
                in: path
                name: id
                description: 'Optional parameter.'
                required: true
                schema:
                    type: string
                examples:
                    omitted:
                        summary: 'When the value is omitted'
                        value: ''
                    present:
                        summary: 'When the value is present'
                        value: necessitatibus
    /admin/admin_dashboard:
        get:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                302:
                    description: ''
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: "<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"0;url='http://localhost/admin/login'\" />\n\n        <title>Redirecting to http://localhost/admin/login</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"http://localhost/admin/login\">http://localhost/admin/login</a>.\n    </body>\n</html>"
            tags:
                - Endpoints
            security: []
    /admin/logout:
        get:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                302:
                    description: ''
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: "<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"0;url='http://localhost/admin/login'\" />\n\n        <title>Redirecting to http://localhost/admin/login</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"http://localhost/admin/login\">http://localhost/admin/login</a>.\n    </body>\n</html>"
            tags:
                - Endpoints
            security: []
    /admin/manufacturers:
        get:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                302:
                    description: ''
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: "<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"0;url='http://localhost/admin/login'\" />\n\n        <title>Redirecting to http://localhost/admin/login</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"http://localhost/admin/login\">http://localhost/admin/login</a>.\n    </body>\n</html>"
            tags:
                - Endpoints
            security: []
